### PR TITLE
Use all-the-package-repos as a source of package names

### LINKED ISSUE #24: [Idea] Updates are a single commit
Currently there are two commits per update. It would be nice if each update is a single unified commit, like we did in https://github.com/nice-registry/all-the-package-repos/pull/13

### LINKED ISSUE #25: Is this project not maintained anymore?
I see the last commit is in 2019.
Can you suggest me where I can get the current list of most downloaded npm packages?

### PR DESCRIPTION
**Pull request by zarianec**
This PR follows the discussion in [this issue](https://github.com/nice-registry/all-the-package-repos/issues/30#issue-980551280) and changes the way names list is built.

Since [all-the-package-repos](https://github.com/nice-registry/all-the-package-repos) package now contains all the packages even if they don't have a repo, it is used to build a separate package names list without need to maintain another NPM changes feed reader.

Caveat of this solution is that now package names are not sorted by dependants.
Both [dependent-counts](https://github.com/nice-registry/dependent-counts) and [dependent-packages](https://github.com/nice-registry/dependent-packages) seems to be broken and doesn't contain valid information at the moment.

resolve #24 
resolve #25

### CODE REVIEW

**Comment by zarianec** [comment]
@jimaek @zeke can you please confirm that `GITHUB_PAT_FROM_ZEKE` and `NPM_TOKEN` secrets set for this repository as they are required for releases.

**Comment by jimaek** [comment]
```
NPM_TOKEN
ZEKE_PAT_WITH_REPO_AND_WORKFLOW_ACCESS
```

**Comment by zeke** [comment]
What @jimaek said :)

Screen Shot 2022-02-04 at 12 57 45 PM

Please @-message me again if I'm blocking you on anything!  💛

**Comment by zeke** [comment]
Nice work, @zarianec 🙌🏼

**Pull request merged**
