### PR TITLE
Fix repo URL

### PR DESCRIPTION
**Pull request by karlhorky**
Hi, thanks for this package! 🙌  Looks useful!

Just a quick PR to correct the incorrect GitHub URL on npm:

Screenshot 2022-12-06 at 18 44 51

### CODE REVIEW

**Comment by karlhorky** [comment]
Funny enough, it seems like @zeke's name on GitHub is cursed with zalgo or something

Screenshot 2022-12-06 at 18 43 50

**Comment by karlhorky** [comment]
Thanks for the merge! 🙌

**Comment by karlhorky** [comment]
Thanks for the merge!

**Comment by zeke** [comment]
Haha!

TIL:

> zalgo (Internet slang) Text that appears corrupted or creepy due to the deliberate overuse of diacritics.

**Pull request merged**
